### ISSUE TITLE
Tags disappear when running if Tags as part of List Item.

### ISSUE THREAD

**Issue by foolbear** [apptekstudios/ASCollectionView#84] opened 2020-01-26 03:46 UTC
**Describe the bug**
I put the demo(TagsScreen) tags into list item, but it disappear when running.
```
ASCollectionView(
				section:
				ASCollectionViewSection(id: 0, data: store.items)
				{ item, _ in
					Text(item.displayString)
						.fixedSize()
						.padding(5)
						.background(Color(.systemGray))
						.cornerRadius(5)
			})
				.layout
			{
				let fl = AlignedFlowLayout()
				fl.estimatedItemSize = UICollectionViewFlowLayout.automaticSize
				return fl
			}
			.shrinkToContentSize(isEnabled: shrinkToSize, $contentSize, dimensionToShrink: .vertical)
```

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**
A description of what you expected to happen.

**Screenshots**

**Xcode Version:**
- 

**Simulator, Device, Both?**
- Where is the problem occuring

**Comment by apptekstudios** [comment] 2020-01-26 08:43
Closing as a duplicate of #76 

This is definitely a reproducible bug and is secondary to a SwiftUI bug, I’ll hopefully have a workaround up soon :)

**Closed by apptekstudios** 2020-01-26 08:43 UTC
