### ISSUE TITLE
XCode 11.2b - EXC_BAD_ACCESS at setupPrefetching()

### ISSUE THREAD

**Issue by janandre** [apptekstudios/ASCollectionView#13] opened 2019-10-16 20:14 UTC
When running the demo project or just using the collection view in an own project it crashes on `setupPrefetching`.

**Comment by apptekstudios** [comment] 2019-10-16 21:19
Thanks for raising the issue Jan :) I couldn’t reproduce this crash, which version of Xcode / iOS are you testing with?

**Comment by janandre** [comment] 2019-10-16 21:20
I used Version 11.2 beta (11B41) :)

**Comment by apptekstudios** [comment] 2019-10-16 21:30
I suspect it's due to some change in Combine (which is utilised for `setupPrefetching`). There's no error on the Xcode 11.1 GM.
I'll download that beta and will try and take a look what's happening later today :)

**Comment by apptekstudios** [comment] 2019-10-17 12:34
Managed to track down the issue and should now be resolved.

It seems to be a weird compiler bug in the beta.
- The same error occurred when I replaced `setupPrefetching` with a completely empty function titled `test`.
- Simply moving the function into an extension fixed the error (as did moving it elsewhere within the Coordinator definition, however I opted to stick with the extension). 

I have tested in Xcode 11.2 beta 2 and the crash is now resolved. It'd be great if you could test the new version I've pushed (0.9.1) and confirm it is now working for you :)

**Comment by apptekstudios** [comment] 2019-10-18 08:19
@janandre Closing this issue after further testing of 0.9.1. Please let me know if you think it needs to be re-opened

**Closed by apptekstudios** 2019-10-18 08:19 UTC
Labels: Resolved

**Comment by janandre** [comment] 2019-10-20 17:21
Works great, thanks!
