### ISSUE TITLE
Enviroment Data lost in SwiftUI view

### ISSUE THREAD

**Issue by ryangittings** [apptekstudios/ASCollectionView#59] opened 2019-12-30 10:58 UTC
When using an environment object, or any data in the environment, e.g. managed object context, it causes an intermittent crash.

**To Reproduce**
Steps to reproduce the behaviour:
- Create standard grid with ASCollectionView
- Using environment to pass data to SwiftUI view (managedObjectContext is a good example)
- Experience crash

**Expected behaviour**
- No crash, or documentation on expected behaviour/implementation?

**Xcode Version:**
- 11.3

**Simulator, Device, Both?**
Both, iOS 11.3.

**Comment by apptekstudios** [comment] 2019-12-30 11:32
Thanks for reporting the issue @ryangittings. This is unexpected behaviour, the environment objects should be getting carried across to the cells...

I haven't been able to reproduce the crash with EnvironmentObject or managedObjectContext. Do you have any simple demo that reproduces the crash?

A few questions to help narrow it down:
- are you accessing the environment / environment object outside of the view body variable?
- Is there an exception logged to the console when crashing?

As a workaround until we find the cause, consider doing the following (passing the environment object directly to your cells):
```swift
struct ContentView: View {
	@EnvironmentObject var yourObject: ObjectType
	
	var body: some View {
		ASCollectionView {
			ASCollectionViewSection(...) { item in
				Text("Your cell contents")
					.environmentObject(self.yourObject)
			}
		}
	}
}
```

**Comment by ryangittings** [comment] 2019-12-30 12:50
I found it was when using a tab view and switching between the tabs. 

Nope it’s in the view body; I’ll see if I can reproduce the exception as soon as I can.

That was the workaround I’ve used, thanks for that!

**Comment by apptekstudios** [comment] 2020-03-02 07:44
Closing this for now as it seems to be resolved in recent versions of SwiftUI. Please feel free to reopen if it recurs :)

**Closed by apptekstudios** 2020-03-02 07:44 UTC

**Comment by kerrmarin** [comment] 2020-04-07 12:44
@apptekstudios I can reproduce the crash always by making these changes https://github.com/kerrmarin/ASCollectionView/commit/cfb538dce625a91fa24168f286a1774cfb3373fd and then navigating the demo app to the "App Store Layout" demo then scrolling the top carousel

**Comment by apptekstudios** [comment] 2020-04-08 08:22
@kerrmarin Thank you for the easy instructions to reproduce the error!

Unfortunately it seems that this is a SwiftUI bug, and I am unable to work around it within the library :(

I would recommend using the workaround I suggested above if utilising EnvironmentObject 👍 


Further info from my debugging:
- Primary issue: SwiftUI is calling the view's `body` immediately on initialising a UIHostingController.
- This means there is no opportunity to add the UIHostingController to the view/VC hierarchy before there is attempted access to the environment object.

**Comment by kerrmarin** [comment] 2020-04-08 09:31
Thanks for the feedback @apptekstudios. Do you think it's worth re-opening this issue until it's fixed? More for visibility than for anything else in case someone else comes looking for an answer :) I'll also open a bug in the Swift bug tracker

**Comment by apptekstudios** [comment] 2020-04-08 11:24
> Thanks for the feedback @apptekstudios. Do you think it's worth re-opening this issue until it's fixed? More for visibility than for anything else in case someone else comes looking for an answer :)

I've created a new issue #131 that outlines the bug and its workaround to make it easy for anyone having the problem :)
