### ISSUE TITLE
Crash on trying to deinit ASCollectionView

### ISSUE THREAD

**Issue by alexandremorgado** [apptekstudios/ASCollectionView#133] opened 2020-04-08 19:24 UTC
**Describe the bug**
Sometimes the app crashes on trying to deinit ASCollectionView. The Xcode logs are the generic 'Fatal error: Attempted to read an unowned reference but object', but on crashlogs I found some references to ASCollectionView: 

```
23  libswiftCore.dylib            	0x00000001bc8b161c _swift_release_dealloc + 36 (HeapObject.cpp:626)
24  libswiftCore.dylib            	0x00000001bc8b2370 bool swift::RefCounts<swift::SideTableRefCountBits>::doDecrement<(swift::PerformDeinit)1>(unsigne... + 252 (RefCount.h:945)
25  SwiftUIPackages               	0x00000001044d6ba8 ASPriorityCache.__deallocating_deinit + 24 (__hidden#4918_:0)
26  libswiftCore.dylib            	0x00000001bc8b161c _swift_release_dealloc + 36 (HeapObject.cpp:626)
27  SwiftUIPackages               	0x0000000104493334 ASCollectionView.Coordinator.deinit + 204 (__hidden#1236_:0)
28  SwiftUIPackages               	0x00000001044933ac ASCollectionView.Coordinator.__deallocating_deinit + 12 (__hidden#1236_:0)
29  libswiftCore.dylib            	0x00000001bc8b161c _swift_release_dealloc + 36 (HeapObject.cpp:626)
30  libswiftCore.dylib            	0x00000001bc8b2370 bool swift::RefCounts<swift::SideTableRefCountBits>::doDecrement<(swift::PerformDeinit)1>(unsigne... + 252 (RefCount.h:945)
31  SwiftUI                       	0x00000001e7073680 destroy for ViewLeafView + 124 (<compiler-generated>:0)
``` 

**To Reproduce**
In my app the problem happens when I push and pop a view with a ASTableView (and 3 sections with ASCollectionViews) for a second or third time.    

**Expected behaviour**
Init and deinit views without crash. 

**Xcode Version:**
- 11.4 

**Simulator, Device, Both?**
- Simulator and devices

**More details**
- I think the problem is related to auto caching on ASCollectionView. I forked the project and deactivated autoCachingHostingControllers then the crash stopped happening.

**Comment by mwilsoncricut** [comment] 2020-04-20 19:31
Seeing this same issue

**Comment by apptekstudios** [comment] 2020-04-20 21:29
@alexandremorgado @mwilsoncricut Have either of you got a simple project that reproduces this? I haven’t been able to reproduce it which is making debugging difficult

**Comment by apptekstudios** [comment] 2020-05-27 02:53
Closing for now as I cannot reproduce. This is potentially a SwiftUI bug as there are no unowned references used in ASCollectionView

**Closed by apptekstudios** 2020-05-27 02:53 UTC

**Comment by alexandremorgado** [comment] 2020-05-27 12:47
Ok @apptekstudios. I'm sorry I didn't post a simple project that reproduces this bug. I have tried, but in a simple project this crash don't doesn't happens.  Thank you for this great lib!
