### ISSUE TITLE
List disappears on layout update

### ISSUE THREAD

**Issue by FaizanDurrani** [apptekstudios/ASCollectionView#90] opened 2020-02-02 21:11 UTC
**Describe the bug**
ASCollectionViewSection disappears entirely when you navigate to a new view and come back. It comes back if you scroll

**To Reproduce**
I don't exactly know? I am using the same code posted in #88 

**Expected behaviour**
List stays visible

**Screenshots**
https://youtu.be/EKA92UlwtuA

**Xcode Version:**
- 11.3.1 (11C504)

**Simulator, Device, Both?**
- Tested on Device: IPhone 6s

**Comment by FaizanDurrani** [comment] 2020-02-02 21:12
This also happens sometimes when you switch to and from Landscape mode

**Comment by apptekstudios** [comment] 2020-02-10 12:53
Sorry for the delay getting back to you. This sounds related to a few issues stemming from SwiftUI skipping some UIKit lifecycle calls...
I'm currently working on a version to patch these issues, will let you know when there's a branch available to test 👍

**Comment by FaizanDurrani** [comment] 2020-02-29 16:17
Any updates to this?

**Comment by FaizanDurrani** [comment] 2020-02-29 22:02
I don't know why but the items in my section seem to be linked to each other
https://youtu.be/h9VKjFQbxlo

**Comment by apptekstudios** [comment] 2020-03-31 12:39
@FaizanDurrani Hopefully these issues should be resolved in the latest version, let me know if there's still problems 👍 

The disappearing sections bug unfortunately seems to be a UICollectionViewCompositionalLayout issue... I was able to reproduce the same bug in a pure UIKit project :(

**Comment by FaizanDurrani** [comment] 2020-03-31 13:19
> @FaizanDurrani Hopefully these issues should be resolved in the latest version, let me know if there's still problems 👍 
> 
> 
> 
> The disappearing sections bug unfortunately seems to be a UICollectionViewCompositionalLayout issue... I was able to reproduce the same bug in a pure UIKit project, so not sure what to do about it other than file a radar :(

Nice, thanks for your hard work.
I’ll try the changes out soon

**Closed** 2020-04-08 11:42 UTC
